---
- name: create initial tenant
  shell: source ~/templates/overcloudrc && openstack project create {{ tenant_name|default('test-drive') }}
  become: yes
  become_user: stack
- name: create initial user
  shell: source ~/templates/overcloudrc && openstack user create --password {{ user_passwd|default('r3dh4t!') }} --project {{ tenant_name|default('test-drive') }} {{ user_name|default('td-user') }}
  become: yes
  become_user: stack
- name: set admin user to admin role on project {{ tenant_name|default('test-drive') }} 
  shell: source ~/templates/overcloudrc && openstack role add --project {{ tenant_name|default('test-drive') }} --user admin admin
  become: yes
  become_user: stack

- name: create project private network
  shell: source ~/templates/overcloudrc && openstack network create --os-project-name {{ tenant_name|default('test-drive') }} private
  become: yes
  become_user: stack

- name: create project private subnet
  shell: source ~/templates/overcloudrc && openstack subnet create --os-project-name {{ tenant_name|default('test-drive') }} --subnet-range 10.10.10.0/24 --network private --allocation-pool start=10.10.10.100,end=10.10.10.200 private-subnet
  become: yes
  become_user: stack

- name: create m1.tiny flavor
  shell: source ~/templates/overcloudrc && openstack flavor create --id 1 --ram 512 --disk 1 --vcpus 1 --public m1.tiny
  become: yes
  become_user: stack

- name: copy cirros image to ospd
  copy:
    src: /tmp/cirros-0.3.5-x86_64-disk.img
    dest: /home/stack/
    owner: stack
    group: stack

- name: upload cirros image to overcloud glance
  shell: source ~/templates/overcloudrc && openstack image create --container-format bare --disk-format qcow2 --file /home/stack/cirros-0.3.5-x86_64-disk.img --public cirros
  become: yes
  become_user: stack

