---
## playbook to deploy an openstack director server

- name: configure the openstack director server and deploy the overcloud
  hosts: director
  remote_user: stack
  roles:
    - ../roles/overcloud-cleanup
