---
- name: import subscription manager information
  include_vars: "rhsm.yaml"

- name: register the server
  redhat_subscription:
    state: present
    activationkey: "{{ director_activation_key }}"
    org_id: "{{ rhsm_org_id }}"
    autosubscribe: true
  register: new_register

- name: If first time - Disable all repos
  shell: subscription-manager repos --disable=*
  when: new_register.changed

- name: Enable repository
  shell: subscription-manager repos --enable {{ item }}
  with_items: "{{ rhsm_repos }}"
  when: new_register.changed

## yum update
- name: update packages
  yum:
    name: '*'
    state: latest
  tags:
  - rhn

## yum packages
- name: install required packages
  yum: 
    name: '{{ item }}'
  tags:
    - rhn
  with_items:
  - python-tripleoclient
  #- rhosp-director-images
  - libguestfs-tools
  - screen
  - vim-enhanced

## set hostname
- name: set hostname in /etc/hosts
  lineinfile: 
    dest: /etc/hosts 
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}  {{ ansible_nodename }}  {{ ansible_hostname }}"
    state: present
    backup: yes
  tags:
    - ospdcfg
- name: set hostname
  hostname:
    name: "{{ ansible_nodename }}"
  tags:
  - ospdcfg

## create stack user (password decrypts to P@ssw0rd)
- name: create stack user
  user:
    name: stack
    shell: /bin/bash
    password: $6$rounds=656000$47cizb4beOY.uB9c$wTlFCrP62g/M0.UNl0IHLOOw.fuWvJwCQLLS8UeruI1T/tbAdKd8Wzhsy7SandrOtROwBn7FBZHTaZcZciXMd/
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags:
  - stackuser
- name: grant sudo to stack
  copy:
    src: stack.sudo
    dest: /etc/sudoers.d/stack
    mode: 0440
  tags:
  - stackuser

## setup stack env
- name: create stack directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: stack
    group: stack
  with_items:
  - /home/stack/images

- name: copy screenrc
  copy:
    src: screenrc
    dest: /home/stack/.screenrc
    owner: stack
    group: stack
  tags:
  - rc
